Repository CorvusOps/Erovoutika_ExamWebsite, pull requests merged in 2022-10, with the labels that each got.

#31 added Admin_ExamList
  admin_examlist.php
  src/css/admin_examlist_style.css
Labels: good first issue

#32 Pushed the initial version of admin edit profile
  admin_profile.html
  src/css/admin_profile_style.css
  src/webadmin/admin_profile.php
Labels: good first issue

#35 Hotfix Client Side of things
  src/webclient/Settings.php
  src/webclient/UserProfile.php
  src/webexam/ExamList.php
Labels: enhancement

#39 added Admin Examinee List and Check Exam UI
  admin_checkexam.php
  admin_examineelist.php
  src/css/admin_checkexam_style.css
  src/css/admin_examineelist_style.css
Labels: good first issue

#40 Debug client side
  src/includes/header.php
  src/webclient/Settings.php
  src/webclient/UserProfile.php
  src/webclient/client_template.php
Labels: bug, enhancement

#42 Admin sync
  admin_examlist.php
  src/webadmin/AdminExamList.php
  src/webadmin/AdminExamineeList.php
  src/webadmin/AdminHome.php
  src/webadmin/AdminProfile.php
  src/webadmin/admin_checkexam.php
  src/webadmin/admin_login.html
  src/webadmin/admin_template.php
  src/webadmin/adminsignup_template.php
Labels: enhancement

#36 Uploaded the User Table Admin Page
  admin_usertable.html
  src/css/admin_usertable_style.css
  src/webadmin/admin_usertable.php
Labels: good first issue

#44 changed cards
  src/css/UserProfileStyle.css
  src/webclient/UserProfile.php
Labels: good first issue

#46 Db sexam list
  src/webclient/UserProfile.php
Labels: enhancement

#45 First Draft for the Exam Editor
  admin_exameditor.html
  src/css/admin_exameditor_style.css
  src/webadmin/admin_exameditor.php
Labels: good first issue

#47 Home page
  index.php
  src/css/homestyle.css
  src/css/loginstyle.css
  src/css/signupstyle.css
  src/images/Backg.png
  src/images/Logo2light.png
  src/images/aboutus.png
  src/images/article1.avif
  src/images/article2.avif
  src/images/article3.avif
  src/images/article4.avif
  src/images/article5.avif
  src/images/article6.avif
  src/images/article7.avif
  src/images/background.jpg
  src/images/contact.jpg
  src/images/login.png
  src/images/services.jpg
  src/images/working2.gif
  src/includes/header.php
  src/login_template.php
  src/signup_template.php
Labels: enhancement

#49 Remove the HEAD on header
  src/includes/header.php
Labels: enhancement, help wanted

#50 modified Exam List Page
  src/css/ExamListStyle.css
  src/webexam/ExamList.php
Labels: enhancement

#52 2.1.N modified Admin Examinee List Page
  src/css/admin_examineelist_style.css
  src/webadmin/AdminExamineeList.php
Labels: enhancement

#51 2.1.N modified Admin Exam List Page
  src/css/admin_examlist_style.css
  src/webadmin/AdminExamList.php
Labels: enhancement

#53 Fix colors of admin home page
  src/css/admin_home_style.css
  src/images/Logo.png
  src/images/logo.png
  src/includes/connectdb.php
  src/webadmin/AdminHome.php
Labels: good first issue

#55 [2.2.1] Add & Fix CRUD
  src/crud/tbusersAddAdmin.php
  src/crud/tbusersAddSignUp.php
  src/crud/tbusersDeleteCL.php
  src/crud/tbusersDeleteST.php
  src/crud/tbusersUserUpdate.php
  src/includes/validation.php
Labels: enhancement

#54 Fix colors of admin profile page
  src/css/admin_profile_style.css
  src/webadmin/AdminProfile.php
Labels: good first issue

#57 first draft. fixed the exam images
  src/css/admin_examlist_style.css
  src/webadmin/AdminExamList.php
Labels: good first issue

#56 first draft for the admin user table
  src/css/admin_usertable_style.css
  src/webadmin/admin_usertable.php
Labels: good first issue

#58 [2.3.5] Minor hotfix onphase2
  src/crud/tbusersAddAdmin.php
  src/crud/tbusersAddSignUp.php
  src/crud/tbusersDeleteCL.php
  src/crud/tbusersDeleteST.php
  src/crud/tbusersUserUpdate.php
  src/signup_template.php
  src/webclient/Settings.php
  src/webexam/ExamList.php
Labels: enhancement

#59 adjusted colors on User Profile
  src/css/UserProfileStyle.css
  src/webclient/UserProfile.php
Labels: enhancement

#60 2.1.8 modified Settings Page
  src/css/SettingsStyle.css
  src/webclient/Settings.php
Labels: enhancement

#61 2.3.3 UI and DB Sync on Admin Side
  src/webadmin/AdminExamList.php
  src/webadmin/AdminHome.php
  src/webadmin/admin_usertable.php
Labels: enhancement

#62 Have put input and form tag and fix the activeicon
  src/webadmin/AdminExamList.php
  src/webadmin/AdminProfile.php
Labels: good first issue

#63 Fix the css of some of the admin pages
  src/css/admin_checkexam_style.css
  src/css/admin_exameditor_style.css
  src/css/admin_examineelist_style.css
  src/webadmin/AdminExamineeList.php
  src/webadmin/admin_checkexam.php
  src/webadmin/admin_exameditor.php
Labels: good first issue
